import sys
import argparse
import time
from stt import SpeechToText
from tts import TextToSpeech
from system_agent import SystemAgent
from brain import JarvisBrain

# Maximum LLM→command→result iterations per user turn (prevents infinite loops)
MAX_AGENTIC_ITERATIONS = 8


def run_agentic_loop(brain, system_agent, tts, user_message):
    """
    Handles the dialogue loop, executing commands generated by the brain
    and feeding results back until a final spoken response is achieved.

    Stops after MAX_AGENTIC_ITERATIONS to prevent runaway loops.
    """
    current_message = user_message

    for iteration in range(1, MAX_AGENTIC_ITERATIONS + 1):

        # 1. Get thought / command from Brain
        response = brain.get_response(current_message)

        # 2. Extract any system command enclosed in <run>...</run>
        cmd_to_run = brain.extract_command(response)

        # 3. Clean up the response for speaking (strip <run> blocks & markdown)
        speech_text = brain.clean_speech_text(response)

        # 4. Speak and display the text response
        if speech_text:
            print(f"\n[JARVIS] {speech_text}")
            tts.speak(speech_text)

        # 5. If there is a command to run, execute it and loop
        if cmd_to_run:
            print(f"[JARVIS] Running: '{cmd_to_run}'")
            exec_result = system_agent.execute_command(cmd_to_run)

            # Format execution result for the brain's next turn
            result_formatted = (
                f"[System Execution Result: status={exec_result['status']}, "
                f"exit_code={exec_result['exit_code']}, "
                f"stdout='{exec_result['stdout']}', "
                f"stderr='{exec_result['stderr']}']\n"
                f"Current working directory is now: {system_agent.get_cwd()}"
            )

            print(f"[JARVIS System] Command finished with exit code {exec_result['exit_code']}.")
            current_message = result_formatted

            if iteration == MAX_AGENTIC_ITERATIONS:
                warning = "I have reached my maximum command iterations for this turn, Sir."
                print(f"\n[JARVIS] {warning}")
                tts.speak(warning)
                break
        else:
            # No command — the response is the final answer
            break


def start_voice_mode(stt, tts, brain, system_agent, wake_word="jarvis"):
    """
    Main loop for fully voice-controlled JARVIS.
    """
    print(f"\n=== JARVIS Voice Controller Active ===")
    print(f"Wake word: '{wake_word}'  |  Press Ctrl+C to exit.\n")

    tts.speak("Systems are online, Sir. I am listening.")

    while True:
        try:
            # 1. Passive listen for wake word (no timeout — waits forever)
            heard = stt.listen(timeout=None, phrase_time_limit=4)
            if not heard:
                continue

            heard_lower = heard.lower()

            # 2. Check for wake word (whole-word match to avoid false positives)
            if wake_word in heard_lower.split() or wake_word in heard_lower:
                print(f"\n[JARVIS] Wake word detected!")

                # Check if a command was spoken right after the wake word
                cleaned_command = heard_lower.replace(wake_word, "").strip(" ,.")

                if cleaned_command:
                    print(f"[JARVIS] Inline command: '{cleaned_command}'")
                    run_agentic_loop(brain, system_agent, tts, cleaned_command)
                else:
                    # Just said "Jarvis" — respond and listen for the command
                    greeting = "Yes, Sir?"
                    print(f"\n[JARVIS] {greeting}")
                    tts.speak(greeting)

                    active_command = stt.listen(timeout=8, phrase_time_limit=12)
                    if active_command:
                        run_agentic_loop(brain, system_agent, tts, active_command)
                    else:
                        timeout_msg = "Apologies Sir, I didn't catch that. Returning to standby."
                        print(f"\n[JARVIS] {timeout_msg}")
                        tts.speak(timeout_msg)

        except KeyboardInterrupt:
            shutdown_msg = "Shutting down systems. Goodbye, Sir."
            print(f"\n[JARVIS] {shutdown_msg}")
            tts.speak(shutdown_msg)
            break
        except Exception as e:
            print(f"[JARVIS Error] Voice loop error: {e}")
            time.sleep(1)


def start_text_mode(tts, brain, system_agent):
    """
    Interactive text terminal mode — useful for testing or when microphone is unavailable.
    """
    print(f"\n=== JARVIS Terminal Controller Active ===")
    print("Type your message. Type 'exit' or 'quit' to shut down.\n")

    tts.speak("Terminal interface active, Sir. Ready for your input.")

    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input:
                continue

            if user_input.lower() in ["exit", "quit"]:
                shutdown_msg = "Shutting down terminal interface. Goodbye, Sir."
                print(f"\n[JARVIS] {shutdown_msg}")
                tts.speak(shutdown_msg)
                break

            run_agentic_loop(brain, system_agent, tts, user_input)

        except KeyboardInterrupt:
            print("\nShutting down...")
            break
        except Exception as e:
            print(f"[JARVIS Error] {e}")


def main():
    parser = argparse.ArgumentParser(description="J.A.R.V.I.S. Personal AI Assistant")
    parser.add_argument("--text", action="store_true", help="Start in interactive text-terminal mode instead of voice")
    args = parser.parse_args()

    # 1. Initialize system agent
    print("[JARVIS] Booting core protocols...")
    system_agent = SystemAgent()
    sys_info = system_agent.get_system_info()

    # 2. Initialize TTS
    tts = TextToSpeech()

    # 3. Initialize STT (voice mode only)
    stt = None
    if not args.text:
        try:
            print("[JARVIS] Calibrating microphone inputs...")
            stt = SpeechToText()
        except Exception as e:
            print(f"[JARVIS STT] Failed to initialize microphone: {e}")
            print("[JARVIS] Switching to Text-Terminal mode automatically.")
            args.text = True

    # 4. Initialize Brain — pass system_agent so brain always reads live cwd
    brain = JarvisBrain(system_info=sys_info, system_agent=system_agent)

    # 5. Start selected mode
    if args.text:
        start_text_mode(tts, brain, system_agent)
    else:
        start_voice_mode(stt, tts, brain, system_agent)


if __name__ == "__main__":
    main()
