import sys
import argparse
import time

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

from .stt import SpeechToText
from .tts import TextToSpeech
from .system_agent import SystemAgent
from .brain import JarvisBrain

# Maximum LLM->command->result iterations per user turn (prevents infinite loops)
MAX_AGENTIC_ITERATIONS = 8


def _safe_speak(tts, text):
    """Speak text, but never crash even if TTS itself is broken."""
    try:
        tts.speak(text)
    except Exception:
        print(f"[JARVIS] (Could not speak: {text})")


def run_agentic_loop(brain, system_agent, tts, user_message):
    """
    Handles the dialogue loop, executing commands generated by the brain
    and feeding results back until a final spoken response is achieved.

    Stops after MAX_AGENTIC_ITERATIONS to prevent runaway loops.
    """
    current_message = user_message

    for iteration in range(1, MAX_AGENTIC_ITERATIONS + 1):

        # 1. Get thought / command from Brain
        response = brain.get_response(current_message)

        if not response or not response.strip():
            fallback = "I did not get a response, Sir. Please try again."
            print(f"\n[JARVIS] {fallback}")
            _safe_speak(tts, fallback)
            break

        # 2. Extract any system command enclosed in <run>...</run>
        cmd_to_run = brain.extract_command(response)

        # 3. Clean up the response for speaking (strip <run> blocks & markdown)
        speech_text = brain.clean_speech_text(response)

        # 4. Speak and display the text response
        if speech_text:
            print(f"\n[JARVIS] {speech_text}")
            _safe_speak(tts, speech_text)

        # 5. If there is a command to run, execute it and loop
        if cmd_to_run:
            print(f"[JARVIS] Running: '{cmd_to_run}'")
            exec_result = system_agent.execute_command(cmd_to_run)

            # Format execution result for the brain's next turn
            result_formatted = (
                f"[System Execution Result]\n"
                f"Status: {exec_result['status']}\n"
                f"Exit Code: {exec_result['exit_code']}\n"
                f"STDOUT:\n{exec_result['stdout']}\n"
                f"STDERR:\n{exec_result['stderr']}\n"
                f"[/System Execution Result]\n"
                f"CWD: {system_agent.get_cwd()}"
            )

            print(f"[JARVIS System] Command finished with exit code {exec_result['exit_code']}.")
            current_message = result_formatted

            if iteration == MAX_AGENTIC_ITERATIONS:
                warning = "I have reached my maximum command iterations for this turn, Sir."
                print(f"\n[JARVIS] {warning}")
                _safe_speak(tts, warning)
                break
        else:
            # No command - the response is the final answer
            break


def start_voice_mode(stt, tts, brain, system_agent, wake_word="jarvis"):
    """
    Main loop for fully voice-controlled JARVIS.

    Flow:
      - PASSIVE mode: waits for wake word endlessly
      - ACTIVE WINDOW: after any response, stays active for 30s so the user
        can ask follow-up questions WITHOUT saying "jarvis" again
    """
    print(f"\n=== JARVIS Voice Controller Active ===")
    print(f"Wake word: '{wake_word}'  |  Press Ctrl+C to exit.\n")
    print("[JARVIS] After each response there is a 30s active window for follow-ups.\n")

    _safe_speak(tts, "Systems are online, Sir. I am listening.")

    consecutive_stt_fails = 0
    STT_FAIL_THRESHOLD = 4

    def _settle_audio():
        """Let the audio system settle after playback before opening mic."""
        import time
        time.sleep(0.3)

    def handle_command(command_text):
        """Process a command and return True (always - keeps the caller clean)."""
        if command_text:
            tts.stop()
            run_agentic_loop(brain, system_agent, tts, command_text)
            _settle_audio()
        return True

    def active_window():
        """
        Stay active for up to 30 s per turn, processing follow-ups without
        requiring the wake word.  Returns when there is a timeout (silence).
        """
        ACTIVE_SECS = 30
        print(f"[JARVIS] Active window open - listening for follow-ups ({ACTIVE_SECS}s silence to exit)...")

        while True:
            follow = stt.listen(timeout=ACTIVE_SECS, phrase_time_limit=20)

            if not follow:
                print("[JARVIS] Active window expired. Returning to standby.")
                return

            follow_lower = follow.lower().strip()
            print(f"[JARVIS STT] Follow-up: '{follow_lower}'")

            # Strip the wake word if the user repeated it (e.g. "jarvis what time is it")
            if wake_word in follow_lower:
                follow_lower = follow_lower.replace(wake_word, "").strip(" ,.")

            if not follow_lower:
                _safe_speak(tts, "Yes Sir?")
                _settle_audio()
                extra = stt.listen(timeout=15, phrase_time_limit=20)
                if extra:
                    follow_lower = extra.lower().strip()
                else:
                    return

            handle_command(follow_lower)

    while True:
        try:
            # -- PASSIVE MODE: wait for wake word --------------------------
            heard = stt.listen(timeout=None, phrase_time_limit=10)

            if not heard:
                consecutive_stt_fails += 1
                if consecutive_stt_fails == STT_FAIL_THRESHOLD:
                    _safe_speak(tts, "Sir, I am having trouble understanding your speech. "
                               "Please check your microphone or speak more clearly.")
                    stt.reset()
                elif consecutive_stt_fails > STT_FAIL_THRESHOLD and consecutive_stt_fails % 8 == 0:
                    _safe_speak(tts, "Still having trouble with speech recognition, Sir.")
                    stt.reset()
                continue

            consecutive_stt_fails = 0
            heard_lower = heard.lower()
            print(f"[JARVIS STT] Heard: '{heard_lower}'")

            # -- Global STOP command: interrupt any playing response ---
            if "stop" in heard_lower.split() or heard_lower.strip().endswith("stop"):
                tts.stop()
                print("[JARVIS] Response stopped.")
                _safe_speak(tts, "Understood, Sir.")
                continue

            # -- Wake-word check -------------------------------------------
            if not (wake_word in heard_lower.split() or wake_word in heard_lower):
                # Not the wake word - ignore (passive mode)
                continue

            print(f"\n[JARVIS] Wake word detected!")

            # Was a command spoken in the same breath as the wake word?
            inline_cmd = heard_lower.replace(wake_word, "").strip(" ,.")

            if inline_cmd:
                print(f"[JARVIS] Inline command: '{inline_cmd}'")
                handle_command(inline_cmd)
            else:
                # Just "Jarvis" alone - greet and listen
                _safe_speak(tts, "Yes, Sir?")
                first_cmd = stt.listen(timeout=15, phrase_time_limit=20)
                if first_cmd:
                    print(f"[JARVIS STT] Command: '{first_cmd}'")
                    handle_command(first_cmd.lower())
                else:
                    _safe_speak(tts, "Apologies Sir, I didn't catch that. Returning to standby.")
                    continue  # Skip active window

            # -- ACTIVE WINDOW: accept follow-ups for 30 s -----------------
            active_window()

        except KeyboardInterrupt:
            shutdown_msg = "Shutting down systems. Goodbye, Sir."
            print(f"\n[JARVIS] {shutdown_msg}")
            _safe_speak(tts, shutdown_msg)
            break
        except Exception as e:
            import traceback
            print(f"[JARVIS Error] Voice loop error: {e}")
            traceback.print_exc()
            _safe_speak(tts, "I encountered an unexpected error. Please check the terminal for details.")
            time.sleep(1)


def start_text_mode(tts, brain, system_agent):
    """
    Interactive text terminal mode - useful for testing or when microphone is unavailable.
    """
    print(f"\n=== JARVIS Terminal Controller Active ===")
    print("Type your message. Type 'exit' or 'quit' to shut down.\n")

    tts.speak("Terminal interface active, Sir. Ready for your input.")

    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input:
                continue

            if user_input.lower() in ["exit", "quit"]:
                shutdown_msg = "Shutting down terminal interface. Goodbye, Sir."
                print(f"\n[JARVIS] {shutdown_msg}")
                _safe_speak(tts, shutdown_msg)
                break

            run_agentic_loop(brain, system_agent, tts, user_input)

        except KeyboardInterrupt:
            print("\nShutting down...")
            break
        except Exception as e:
            print(f"[JARVIS Error] {e}")
            _safe_speak(tts, f"An error occurred: {e}")


def main():
    parser = argparse.ArgumentParser(description="J.A.R.V.I.S. Personal AI Assistant")
    parser.add_argument("--text", action="store_true", help="Start in interactive text-terminal mode instead of voice")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose debug output")
    args = parser.parse_args()

    # 1. Initialize system agent
    print("[JARVIS] Booting core protocols...")
    system_agent = SystemAgent()
    sys_info = system_agent.get_system_info()

    # 2. Initialize TTS
    tts = TextToSpeech()

    # 3. Initialize STT (voice mode only)
    stt = None
    if not args.text:
        try:
            print("[JARVIS] Calibrating microphone inputs...")
            stt = SpeechToText()
        except Exception as e:
            print(f"[JARVIS STT] Failed to initialize microphone: {e}")
            _safe_speak(tts, "Microphone initialization failed. Switching to text mode.")
            print("[JARVIS] Switching to Text-Terminal mode automatically.")
            args.text = True

    # 4. Initialize Brain - pass system_agent so brain always reads live cwd
    brain = JarvisBrain(system_info=sys_info, system_agent=system_agent, debug=args.verbose)

    # 5. Start selected mode
    print(f"[JARVIS] Brain provider: {brain.provider} | Model: {brain.model_name or 'N/A'}")
    if args.text:
        start_text_mode(tts, brain, system_agent)
    else:
        start_voice_mode(stt, tts, brain, system_agent)


if __name__ == "__main__":
    main()
