import argparse
import time
from typing import Any, Optional

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

from .config import STT_FAIL_THRESHOLD, ACTIVE_SECS
from .stt import SpeechToText
from .tts import TextToSpeech
from .system_agent import SystemAgent
from .brain import JarvisBrain
from .agentic_loop import generate_agentic_loop


def _safe_speak(tts: TextToSpeech, text: str) -> None:
    """Speak text, but never crash even if TTS itself is broken."""
    try:
        tts.speak(text)
    except Exception:
        print(f"[JARVIS] (Could not speak: {text})")


def run_agentic_loop(brain: JarvisBrain, system_agent: SystemAgent, tts: TextToSpeech, user_message: str) -> None:
    """
    Handles the dialogue loop, executing commands generated by the brain
    and feeding results back until a final spoken response is achieved.
    Uses the shared ``generate_agentic_loop`` generator internally.
    """
    spoken_anything = False

    for event in generate_agentic_loop(brain, system_agent, user_message):
        if event["type"] == "assistant_response":
            text = event["content"]
            print(f"\n[JARVIS] {text}")
            _safe_speak(tts, text)
            spoken_anything = True
        elif event["type"] == "command":
            print(f"[JARVIS] Running: '{event['content']}'")
        elif event["type"] == "command_output":
            print(f"[JARVIS System] Command finished with exit code {event['exit_code']}.")
        elif event["type"] == "error":
            print(f"[JARVIS Error] {event['content']}")
            _safe_speak(tts, f"An error occurred: {event['content']}")
            spoken_anything = True

    if not spoken_anything:
        final_msg = "Done, Sir."
        print(f"\n[JARVIS] {final_msg}")
        _safe_speak(tts, final_msg)


def start_voice_mode(stt: SpeechToText, tts: TextToSpeech, brain: JarvisBrain, system_agent: SystemAgent, wake_word: str = "jarvis") -> None:
    """
    Main loop for fully voice-controlled JARVIS.

    Flow:
      - PASSIVE mode: waits for wake word endlessly
      - ACTIVE WINDOW: after any response, stays active for 30s so the user
        can ask follow-up questions WITHOUT saying "jarvis" again
    """
    print(f"\n=== JARVIS Voice Controller Active ===")
    print(f"Wake word: '{wake_word}'  |  Press Ctrl+C to exit.\n")
    print("[JARVIS] After each response there is a 30s active window for follow-ups.\n")

    _safe_speak(tts, "Systems are online, Sir. I am listening.")

    consecutive_stt_fails: int = 0

    def _settle_audio() -> None:
        """Let the audio system settle after playback before opening mic."""
        time.sleep(0.5)

    def handle_command(command_text: str) -> bool:
        """Process a command and return True (always - keeps the caller clean)."""
        if command_text:
            tts.stop()
            run_agentic_loop(brain, system_agent, tts, command_text)
            _settle_audio()
        return True

    def active_window() -> None:
        """
        Stay active for up to ACTIVE_SECS per turn, processing follow-ups without
        requiring the wake word.  Returns when there is a timeout (silence).
        """
        print(f"[JARVIS] Active window open - listening for follow-ups ({ACTIVE_SECS}s silence to exit)...")

        while True:
            follow = stt.listen(timeout=ACTIVE_SECS, phrase_time_limit=20)

            if not follow:
                print("[JARVIS] Active window expired. Returning to standby.")
                return

            follow_lower = follow.lower().strip()
            print(f"[JARVIS STT] Follow-up: '{follow_lower}'")

            # Strip the wake word if the user repeated it (e.g. "jarvis what time is it")
            if wake_word in follow_lower:
                follow_lower = follow_lower.replace(wake_word, "").strip(" ,.")

            if not follow_lower:
                _safe_speak(tts, "Yes Sir?")
                _settle_audio()
                extra = stt.listen(timeout=15, phrase_time_limit=20)
                if extra:
                    follow_lower = extra.lower().strip()
                else:
                    return

            handle_command(follow_lower)
            stt.reset()
            time.sleep(0.5)

    while True:
        try:
            # -- PASSIVE MODE: wait for wake word --------------------------
            heard = stt.listen(timeout=None, phrase_time_limit=10)

            if not heard:
                consecutive_stt_fails += 1
                if consecutive_stt_fails == STT_FAIL_THRESHOLD:
                    _safe_speak(tts, "Sir, I am having trouble understanding your speech. "
                               "Please check your microphone or speak more clearly.")
                    stt.reset()
                elif consecutive_stt_fails > STT_FAIL_THRESHOLD and consecutive_stt_fails % 8 == 0:
                    _safe_speak(tts, "Still having trouble with speech recognition, Sir.")
                    stt.reset()
                continue

            consecutive_stt_fails = 0
            heard_lower = heard.lower()
            print(f"[JARVIS STT] Heard: '{heard_lower}'")

            # -- Global STOP command: interrupt any playing response ---
            if "stop" in heard_lower.split() or heard_lower.strip().endswith("stop"):
                tts.stop()
                print("[JARVIS] Response stopped.")
                _safe_speak(tts, "Understood, Sir.")
                continue

            # -- Wake-word check -------------------------------------------
            if not (wake_word in heard_lower.split() or wake_word in heard_lower):
                # Not the wake word - ignore (passive mode)
                continue

            print(f"\n[JARVIS] Wake word detected!")

            # Was a command spoken in the same breath as the wake word?
            inline_cmd = heard_lower.replace(wake_word, "").strip(" ,.")

            if inline_cmd:
                print(f"[JARVIS] Inline command: '{inline_cmd}'")
                handle_command(inline_cmd)
            else:
                # Just "Jarvis" alone - greet and listen
                _safe_speak(tts, "Yes, Sir?")
                first_cmd = stt.listen(timeout=15, phrase_time_limit=20)
                if first_cmd:
                    print(f"[JARVIS STT] Command: '{first_cmd}'")
                    handle_command(first_cmd.lower())
                else:
                    _safe_speak(tts, "Apologies Sir, I didn't catch that. Returning to standby.")
                    continue  # Skip active window

            # -- ACTIVE WINDOW: accept follow-ups for 30 s -----------------
            active_window()

        except KeyboardInterrupt:
            shutdown_msg = "Shutting down systems. Goodbye, Sir."
            print(f"\n[JARVIS] {shutdown_msg}")
            _safe_speak(tts, shutdown_msg)
            break
        except Exception as e:
            import traceback
            print(f"[JARVIS Error] Voice loop error: {e}")
            traceback.print_exc()
            _safe_speak(tts, "I encountered an unexpected error. Please check the terminal for details.")
            time.sleep(1)


def start_text_mode(tts: TextToSpeech, brain: JarvisBrain, system_agent: SystemAgent) -> None:
    """
    Interactive text terminal mode - useful for testing or when microphone is unavailable.
    """
    print(f"\n=== JARVIS Terminal Controller Active ===")
    print("Type your message. Type 'exit' or 'quit' to shut down.\n")

    tts.speak("Terminal interface active, Sir. Ready for your input.")

    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input:
                continue

            if user_input.lower() in ["exit", "quit"]:
                shutdown_msg = "Shutting down terminal interface. Goodbye, Sir."
                print(f"\n[JARVIS] {shutdown_msg}")
                _safe_speak(tts, shutdown_msg)
                break

            run_agentic_loop(brain, system_agent, tts, user_input)

        except KeyboardInterrupt:
            print("\nShutting down...")
            break
        except Exception as e:
            print(f"[JARVIS Error] {e}")
            _safe_speak(tts, f"An error occurred: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(description="J.A.R.V.I.S. Personal AI Assistant")
    parser.add_argument("--text", action="store_true", help="Start in interactive text-terminal mode instead of voice")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose debug output")
    args = parser.parse_args()

    # 1. Initialize system agent
    print("[JARVIS] Booting core protocols...")
    system_agent = SystemAgent()
    sys_info = system_agent.get_system_info()

    # 2. Initialize TTS
    tts = TextToSpeech()

    # 3. Initialize STT (voice mode only)
    stt = None
    if not args.text:
        try:
            print("[JARVIS] Calibrating microphone inputs...")
            stt = SpeechToText()
        except Exception as e:
            print(f"[JARVIS STT] Failed to initialize microphone: {e}")
            _safe_speak(tts, "Microphone initialization failed. Switching to text mode.")
            print("[JARVIS] Switching to Text-Terminal mode automatically.")
            args.text = True

    # 4. Initialize Brain - pass system_agent so brain always reads live cwd
    brain = JarvisBrain(system_info=sys_info, system_agent=system_agent, debug=args.verbose)

    # 5. Start selected mode
    print(f"[JARVIS] Brain provider: {brain.provider} | Model: {brain.model_name or 'N/A'}")
    if args.text:
        start_text_mode(tts, brain, system_agent)
    else:
        start_voice_mode(stt, tts, brain, system_agent)


if __name__ == "__main__":
    main()
